# Generated by Django 5.2.13 on 2026-04-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_free_time_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date', 'start_time', '-created_at'], 'verbose_name': '预约记录', 'verbose_name_plural': '预约记录'},
        ),
    ]
