# Generated by Django 5.2.13 on 2026-04-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_seat_map_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['map_row', 'map_col', 'seat_code'], 'verbose_name': '座位', 'verbose_name_plural': '座位'},
        ),
    ]
