# Generated by OpenAI on 2026-04-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='learning_materials/%Y/%m/')),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学习资料',
                'verbose_name_plural': '学习资料',
                'ordering': ['-created_at'],
            },
        ),
    ]
