# Generated by OpenAI on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='是否共享'),
        ),
    ]
